In [1]:
import pandas as pd
import pymysql
from tqdm import tqdm
import os
import pickle

# DB 연결 함수

In [3]:
def connect_db():
    return pymysql.connect(
        host="127.0.0.1",
        user='root',
        password='240812',
        database='lol_data',
        port=3307
    )

# 챔피언 ID, 태그 사전 파일 저장 함수

In [17]:
def get_champion_dict(conn):
    champion_dict_query = "SELECT champion_id, champion_name, tags FROM champion_dict"
    champion_dict = pd.read_sql_query(champion_dict_query, conn)
    with open("table_data/champion_dict.pkl", "wb") as f:
        pickle.dump(champion_dict, f)
    return dict(zip(champion_dict['champion_id'], champion_dict['champion_name']))
conn = connect_db()
get_champion_dict(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_6472\3920025925.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_dict = pd.read_sql_query(champion_dict_query, conn)

# 챔피언 참여자ID 라인타입 사전 파일 저장 함수

In [18]:
def get_champion_participant_id(conn):
    champion_participant_id_query = "SELECT match_id, participant_id, champion_id, position FROM champion_participant_id"
    champion_participant_id = pd.read_sql_query(champion_participant_id_query, conn)
    with open("table_data/champion_participant_id.pkl", "wb") as f:
        pickle.dump(champion_participant_id, f)
    return champion_participant_id
conn = connect_db()
get_champion_participant_id(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_6472\3442806052.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_participant_id = pd.read_sql_query(champion_participant_id_query, conn)

# 게임 종료 파일 저장 함수

In [6]:
def get_game_end(conn):
    game_end_query = "SELECT match_id, real_timestamp, timestamp, winning_team FROM game_end"
    game_end = pd.read_sql_query(game_end_query, conn)
    with open("table_data/game_end.pkl", "wb") as f:
        pickle.dump(game_end, f)
    return game_end
conn = connect_db()
get_game_end(conn)
conn.close()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_6472\226839149.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  game_end = pd.read_sql_query(game_end_query, conn)

# 태그별 평균 수치 데이터 파일 저장함수

In [52]:
def tag_avg_stat():
    with open("dashboard_data/champion_stats.pkl", "rb") as f:
        champion_dataframes = pickle.load(f)

    with open("table_data/champion_dict.pkl", "rb") as f:
        champion_dict = pickle.load(f)

    # 챔피언 딕셔너리 데이터프레임 변환
    champion_df = pd.DataFrame(champion_dict)
    
    # 원하는 태그 매핑 이름 정의
    tag_mapping = {
        "Assassin": "암살자",
        "Fighter": "전사",
        "Mage": "마법사",
        "Marksman": "원거리 공격",
        "Support": "지원가",
        "Tank": "탱커"
    }

    # 결과를 저장할 딕셔너리
    tag_avg_dataframes = {}

    # 태그별 평균 계산
    for tag in set(tag for tags in champion_df['tags'] for tag in eval(tags)):

        # 해당 태그를 가진 챔피언 목록 필터링
        champions_with_tag = champion_df[champion_df['tags'].apply(lambda x: tag in eval(x))]['champion_name'].tolist()
        
        # 태그에 해당하는 챔피언들의 데이터 합산 및 평균 계산
        tag_data = pd.concat([champion_dataframes[champion] for champion in champions_with_tag if champion in champion_dataframes])
        
        # 각 분(minute)마다의 평균을 구함
        tag_avg_df = tag_data.groupby("분").mean().reset_index()


        mapped_tag = tag_mapping.get(tag, tag)  # tag_mapping에 없으면 원래 태그 이름 사용
        tag_avg_dataframes[mapped_tag] = tag_avg_df

    # 최종 태그별 평균 데이터 저장
    with open("dashboard_data/tag_avg_stats.pkl", "wb") as f:
        pickle.dump(tag_avg_dataframes, f)

    print("Tag-based average stats saved to tag_avg_stats.pkl")
tag_avg_stat()

Tag-based average stats saved to tag_avg_stats.pkl

In [55]:
with open("dashboard_data/tag_avg_stats.pkl", "rb") as f:
    data = pickle.load(f)
data['암살자']

,분,챔피언에게 가한 피해량,받은 피해량,총 획득한 골드량,총 경험치량,평균 누적 와드 설치 횟수,평균 누적 와드 제거 횟수
0,0,0.000000,0.000000,500.000000,0.000000,1.001384,1.001105
1,1,37.190909,40.277273,509.090909,0.381818,1.012552,1.022814
2,2,206.363636,452.188636,613.456818,216.065909,1.057364,1.091973
3,3,513.815909,1109.261364,979.215909,741.227273,1.328016,1.064061
4,4,883.986364,1699.111364,1352.297727,1171.547727,2.003402,1.122814
5,5,1267.227273,2299.868182,1724.281818,1616.665909,2.285352,1.150950
6,6,1651.347727,2939.709091,2093.354545,2067.054545,2.660780,1.200677
7,7,2095.388636,3671.975000,2462.718182,2491.743182,3.346120,1.306948
8,8,2562.150000,4425.843182,2863.747727,2971.970455,3.716641,1.438280
9,9,3068.165909,5217.515909,3270.765909,3451.877273,4.208959,1.579148
10,10,3621.927273,6041.909091,3667.456818,3915.488636,4.906655,1.754132
11,11,4257.654545,6936.229545,4107.247727,4422.088636,5.384116,1.948223
12,12,4940.834091,7895.668182,4552.343182,4898.297727,5.957934,2.137525
13,13,5628.197727,8845.984091,4982.245455,5359.859091,6.678416,2.350475
14,14,6334.734091,9824.918182,5454.536364,5880.193182,7.254943,2.559066
15,15,7101.477273,10879.675000,5933.400000,6399.954545,7.906700,2.815268
16,16,7824.163636,11861.831818,6389.165909,6927.615909,8.644430,3.042161
17,17,8620.113636,12889.636364,6857.972727,7459.154545,9.244848,3.327405
18,18,9508.236364,13990.613636,7332.406818,7985.715909,9.894084,3.573868
19,19,10415.406818,15104.563636,7789.238636,8500.702273,10.568686,3.879343
20,20,11325.254545,16220.388636,8243.527273,9019.584091,11.170298,4.171300
21,21,12310.763636,17443.229545,8707.393182,9573.345455,11.866895,4.431343
22,22,13317.300000,18739.050000,9172.968182,10142.538636,12.600302,4.771441
23,23,14426.740909,20074.243182,9648.102273,10708.409091,13.302148,5.131552
24,24,15541.995455,21387.684091,10104.947727,11248.986364,14.160909,5.386927
25,25,16653.788636,22734.540909,10550.863636,11770.556818,14.880555,5.712764
26,26,17816.084091,24076.647727,11002.325000,12311.529545,15.638457,6.030786
27,27,18926.754545,25413.563636,11457.547727,12864.893182,16.245005,6.325802
28,28,20146.704545,26746.202273,11941.790909,13445.690909,17.141091,6.635400
29,29,21350.236364,28178.747727,12416.368182,14023.952273,17.875316,7.086650
30,30,22483.713636,29589.720455,12845.911364,14570.329545,18.810452,7.318050
31,31,23831.802273,31065.784091,13306.843182,15143.113636,19.320884,7.623930
32,32,24983.881818,32531.740909,13721.811364,15685.277273,20.468327,7.877864
33,33,26138.352273,33854.875000,14153.922727,16232.245455,20.724014,8.283323
34,34,27431.786364,35447.140909,14577.300000,16798.059091,21.708825,8.403836
35,35,28741.500000,36856.429545,15019.772727,17345.461364,22.957686,8.920325
36,36,30086.836364,38354.702273,15436.556818,17861.931818,23.753057,8.851859
37,37,31212.625000,39930.152273,15810.818182,18366.997727,24.923767,9.165307
38,38,32446.225000,41407.534091,16278.600000,18980.990909,26.937422,10.016137
39,39,33958.040909,43018.727273,16682.963636,19516.243182,27.194243,9.825735
40,40,35357.825000,44401.570455,17115.470455,20005.640909,28.934079,9.924257
41,41,36438.113636,46136.395455,17554.577273,20631.484091,31.975194,10.831734
42,42,36470.004545,47227.384091,17775.818182,20949.034091,33.503439,11.716987
43,43,38333.840476,48506.714286,18040.738095,21502.266667,35.665027,10.817138
44,44,40038.659524,50009.173810,18437.576190,21781.142857,42.266646,11.628092
45,45,41019.053659,51263.860976,18957.014634,22404.817073,44.480059,11.959845
46,46,42741.305128,53754.943590,19338.171795,22949.528205,41.802780,11.382613
47,47,43822.755882,54966.902941,19022.655882,22527.161765,46.297438,13.000000
48,48,43387.013333,56456.986667,19018.280000,23051.300000,51.484845,9.200000
49,49,44086.969231,54448.584615,19949.919231,24027.765385,57.291663,20.857143
50,50,46046.650000,56893.725000,20045.420833,24368.954167,51.500000,12.333333
51,51,48536.960000,58503.995000,20581.025000,25315.415000,102.416650,13.750000
52,52,53669.127273,61257.772727,21077.072727,25655.954545,68.000000,NaN
53,53,58234.428571,64289.928571,21305.000000,25368.714286,NaN,NaN

# 이벤트 파일 합치는 함수

In [45]:
def load_and_merge_champion_data():
    # 챔피언 데이터 로드
    with open("dashboard_data/champion_main_stats.pkl", "rb") as f:
        champion_main_stats = pickle.load(f)
    
    with open("dashboard_data/champion_ward_placement_stats.pkl", "rb") as f:
        champion_ward_placement_stats = pickle.load(f)
    
    with open("dashboard_data/champion_ward_removal_stats.pkl", "rb") as f:
        champion_ward_removal_stats = pickle.load(f)
    
    merged_data = {}

    for champion_name in champion_main_stats.keys():
        main_stats = champion_main_stats.get(champion_name)
        placement_stats = champion_ward_placement_stats.get(champion_name)
        removal_stats = champion_ward_removal_stats.get(champion_name)
        
        # 분 기준으로 병합
        merged_df = pd.merge(main_stats, placement_stats, on='분', how='outer')
        merged_df = pd.merge(merged_df, removal_stats, on='분', how='outer')
        
        # 분 기준으로 정렬하고 중간 NaN 방지
        merged_df = merged_df.sort_values('분').reset_index(drop=True)
        
        # 병합된 데이터프레임을 딕셔너리에 저장
        merged_data[champion_name] = merged_df
    
    with open("dashboard_data/champion_stats.pkl", "wb") as f:
        pickle.dump(merged_data, f)

In [46]:
load_and_merge_champion_data()

In [47]:
with open("dashboard_data/champion_stats.pkl", "rb") as f:
    data = pickle.load(f)
data

{'애니':      분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량  평균 누적 와드 설치 횟수  \
 0    0           0.0      0.0      500.0      0.0          1.0000
 1    1          51.1     38.8      515.8      0.7          1.0000
 2    2         270.4    239.2      629.0    218.4          1.0185
 3    3         616.7    574.5      962.6    805.3          1.2028
 4    4         939.6    917.2     1279.3   1294.2          1.9385
 5    5        1237.7   1274.8     1618.8   1828.5          2.0708
 6    6        1625.4   1673.7     1957.4   2341.2          2.3812
 7    7        2152.7   2084.7     2313.8   2814.0          3.1545
 8    8        2647.7   2525.0     2692.2   3329.7          3.5296
 9    9        3221.3   3003.7     3085.4   3841.4          4.1809
 10  10        3751.6   3456.1     3439.8   4309.7          4.8265
 11  11        4356.3   3983.3     3858.2   4845.2          5.1546
 12  12        5051.5   4579.7     4283.4   5344.8          5.8474
 13  13        5748.2   5174.8     4661.9   5768.5          6.4708
 14  14        6489.0   5786.7     5086.3   6262.6          7.0000
 15  15        7318.2   6399.1     5538.5   6744.0          8.5547
 16  16        8179.9   7039.1     5918.6   7223.9          8.5783
 17  17        9118.5   7711.3     6316.8   7695.9          9.4016
 18  18       10078.8   8440.0     6760.1   8181.8         11.1053
 19  19       11197.4   9053.0     7188.9   8702.6         11.6983
 20  20       12250.3   9726.7     7580.4   9133.9         12.3333
 21  21       13599.5  10656.3     7995.9   9639.7         13.0000
 22  22       14483.7  11412.9     8373.3  10162.8         13.2301
 23  23       15854.3  12173.7     8858.1  10703.6         14.8315
 24  24       16717.5  13103.2     9080.6  11013.3         15.6582
 25  25       18199.0  13992.2     9520.7  11521.9         18.0678
 26  26       19086.2  14927.0     9854.7  11976.5         20.7347
 27  27       20379.1  15820.1    10146.6  12372.3         20.4800
 28  28       21384.8  16807.7    10510.7  12711.8         22.3636
 29  29       23278.6  17715.9    10958.7  13334.4         21.5476
 30  30       24498.9  18283.3    11426.6  13931.3         25.4286
 31  31       26606.1  19520.0    11811.6  14400.2         21.3214
 32  32       26449.6  20111.1    12068.5  14806.6         29.6875
 33  33       29204.4  21501.2    12591.8  15538.3         32.4615
 34  34       28535.2  21021.2    12664.6  15631.8         35.0000
 35  35       27960.6  23505.1    12386.2  15705.2         44.2000
 36  36       30858.7  23770.2    13304.5  16429.4         18.1667
 37  37       34626.2  25428.9    14243.8  17955.5         49.0000
 38  38       34622.9  26069.0    14024.1  18190.0         32.6667
 39  39       36250.9  28674.4    14035.2  18111.1             NaN
 40  40       36592.6  27927.8    14536.8  19230.1         12.0000
 41  41       41404.5  30839.3    14875.7  19177.9             NaN
 42  42       34934.0  24003.5    16380.0  21965.0         15.0000
 43  43       35270.5  25604.5    16723.0  22313.5             NaN
 44  44       39424.0  25599.7    17681.3  22863.0         16.0000
 45  45       29921.0  26904.0    17002.0  23990.0             NaN
 46  46       30778.0  30635.0    17225.0  24200.0             NaN

     평균 누적 와드 제거 횟수
 0           1.0000
 1           1.0000
 2           1.0000
 3           1.1667
 4           1.1111
 5           1.0833
 6           1.1176
 7           1.2449
 8           1.2241
 9           1.3488
 10          1.6092
 11          1.7865
 12          1.9364
 13          2.0900
 14          2.5313
 15          2.5306
 16          2.6250
 17          3.1975
 18          3.2159
 19          3.5625
 20          3.7439
 21          4.1196
 22          4.7391
 23          5.1176
 24          4.4247
 25          5.4423
 26          5.4167
 27          4.8667
 28          5.5278
 29          7.0870
 30          6.9310
 31          7.4667
 32          6.3636
 33          8.8333
 34          9.7143
 35         12.8333
 36         14.0000
 37          9.0000
 38         10.0000
 39         14.0000
 40          9.0000
 41             NaN
 42         15.0000
 43             NaN
 44             NaN
 45             NaN
 46             NaN  ,
 '올라프':      분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량  평균 누적 와드 설치 횟수  \
 0    0           0.0      0.0      500.0      0.0          1.0000
 1    1          49.3     55.1      509.6      0.5          1.0000
 2    2         346.8    417.2      603.3    165.7          1.0000
 3    3         705.4   1005.3      969.6    771.3          1.0437
 4    4        1033.4   1514.6     1282.9   1229.6          1.7472
 5    5        1492.5   2134.0     1648.0   1781.2          1.8449
 6    6        1937.5   2766.8     1995.1   2282.2          1.9336
 7    7        2448.0   3462.6     2362.4   2772.2          2.6924
 8    8        2980.1   4175.9     2756.1   3313.5          2.8414
 9    9        3542.5   4936.7     3146.5   3850.7          2.9211
 10  10        4150.0   5728.8     3523.8   4367.6          3.6775
 11  11        4779.3   6603.8     3958.7   4937.0          3.8446
 12  12        5470.6   7546.9     4399.7   5450.6          4.0776
 13  13        6184.1   8513.9     4848.4   5951.1          4.6886
 14  14        6923.0   9531.2     5370.0   6522.9          4.8553
 15  15        7736.8  10647.1     5879.2   7076.2          5.1046
 16  16        8424.5  11634.5     6319.2   7612.4          5.7583
 17  17        9266.4  12851.7     6789.5   8149.4          5.9258
 18  18       10130.0  14060.1     7293.4   8706.1          6.1787
 19  19       11163.1  15285.9     7817.1   9295.3          6.8072
 20  20       11991.3  16509.3     8240.7   9786.1          6.8687
 21  21       13144.8  17968.8     8767.6  10385.6          7.3896
 22  22       14130.5  19322.9     9285.5  10989.0          7.8442
 23  23       15378.0  20837.1     9756.7  11548.1          7.9438
 24  24       16639.6  22446.1    10228.1  12075.0          8.6983
 25  25       17741.0  24015.5    10672.0  12604.0          8.6809
 26  26       18599.9  25424.5    11114.1  13091.3          8.9558
 27  27       19642.4  26977.9    11451.5  13563.5          9.4324
 28  28       20859.1  28628.2    12035.7  14210.7          9.9419
 29  29       21867.2  29949.9    12444.7  14784.6         10.4384
 30  30       23018.1  31775.4    12757.5  15189.1         11.1000
 31  31       24848.0  33496.8    13348.6  15957.3         11.2941
 32  32       26138.1  35533.8    13752.2  16404.7         11.6923
 33  33       27212.4  36618.3    14152.4  16900.4         12.0833
 34  34       28630.5  38445.3    14575.7  17521.2         11.9444
 35  35       29620.6  40589.1    15003.6  17921.3         11.6667
 36  36       31413.6  42422.6    15392.2  18385.8         11.6429
 37  37       31828.7  43234.5    15851.8  19149.2         13.0000
 38  38       32972.9  44867.3    16182.8  19691.7         15.0000
 39  39       36451.5  48580.9    16617.0  20149.8         13.6667
 40  40       32221.8  49297.5    16487.8  20103.6         11.0000
 41  41       33098.2  51306.6    17693.8  21708.1         14.2500
 42  42       26384.4  46570.4    17569.3  22087.3         17.5000
 43  43       34604.7  52578.9    18008.1  23425.3             NaN
 44  44       40163.0  54116.3    18976.7  24720.0         19.0000
 45  45       40214.3  54410.7    19429.3  25436.0             NaN
 46  46       42101.0  58067.0    19889.7  25970.0         20.0000
 47  47       42788.8  60547.2    20668.8  26926.2             NaN
 48  48       46122.5  62530.0    19818.0  27129.5             NaN
 49  49       51017.0  67333.0    20497.5  27672.5         21.0000
 50  50       53066.0  69016.3    20518.3  27659.3         22.0000
 51  51       47518.0  69671.5    22041.0  29163.0             NaN

     평균 누적 와드 제거 횟수
 0           1.0000
 1           1.0000
 2           1.1667
 3           1.0769
 4           1.0435
 5           1.1111
 6           1.0909
 7           1.2923
 8           1.2188
 9           1.3462
 10          1.3415
 11          1.4455
 12          1.6373
 13          1.6829
 14          1.7594
 15          1.8662
 16          1.9610
 17          2.2025
 18          2.3198
 19          2.4545
 20          2.9036
 21          2.8986
 22          3.2071
 23          3.2800
 24          3.5377
 25          3.7019
 26          4.1910
 27          4.7000
 28          4.9531
 29          4.6792
 30          5.0213
 31          5.8235
 32          4.8056
 33          6.7647
 34          6.0714
 35          5.7500
 36          7.3000
 37          6.7143
 38          7.0000
 39          7.7500
 40          2.0000
 41          5.0000
 42             NaN
 43             NaN
 44             NaN
 45             NaN
 46             NaN
 47             NaN
 48             NaN
 49             NaN
 50          7.0000
 51             NaN  ,
 '갈리오':      분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량  평균 누적 와드 설치 횟수  \
 0    0           0.0      0.0      500.0      0.0          1.0000
 1    1          29.9     47.9      505.1      0.4          1.0025
 2    2         201.7    333.1      595.9    213.4          1.0110
 3    3         553.6    872.4      916.6    798.4          1.2257
 4    4         918.0   1377.0     1240.6   1280.0          1.9155
 5    5        1332.0   1930.4     1593.7   1800.8          2.1500
 6    6        1730.8   2476.6     1946.4   2316.3          2.4558
 7    7        2174.2   3057.2     2287.5   2751.1          3.1686
 8    8        2617.3   3666.4     2662.8   3255.5          3.5041
 9    9        3087.0   4327.2     3036.1   3758.6          4.1221
 10  10        3586.5   5035.1     3373.5   4209.7          4.7875
 11  11        4190.7   5873.8     3777.1   4731.0          5.3122
 12  12        4849.4   6756.5     4184.8   5215.8          6.1509
 13  13        5461.4   7586.7     4548.5   5645.9          6.7012
 14  14        6076.6   8460.2     4956.6   6144.6          7.5234
 15  15        6749.8   9418.3     5362.0   6620.7          8.7052
 16  16        7393.7  10339.8     5754.2   7126.0          9.1390
 17  17        8133.8  11320.6     6157.0   7614.2         10.4052
 18  18        8852.5  12342.0     6553.0   8092.2         11.7024
 19  19        9625.1  13410.3     6934.9   8566.1         11.9111
 20  20       10369.5  14461.2     7303.1   9021.2         13.1626
 21  21       11189.0  15647.4     7668.6   9515.4         13.6470
 22  22       12061.8  16799.5     8078.6  10056.1         14.5503
 23  23       12951.0  18124.5     8432.5  10543.4         16.2269
 24  24       13878.9  19412.1     8826.1  11042.6         16.6114
 25  25       14891.1  20719.2     9211.5  11528.5         18.4141
 26  26       15838.5  22015.3     9587.7  12033.7         20.0161
 27  27       16666.9  23304.0     9967.5  12546.9         19.6779
 28  28       17448.1  24568.6    10294.0  13004.1         21.5592
 29  29       18523.1  25989.6    10695.8  13537.8         23.0590
 30  30       19536.3  27399.7    11032.1  14058.5         22.6411
 31  31       20442.2  29179.8    11406.5  14616.2         23.1992
 32  32       21376.9  30587.7    11701.2  15061.7         24.3681
 33  33       22205.3  31781.0    12041.6  15550.9         26.5234
 34  34       22942.5  32992.4    12437.7  16141.0         28.7521
 35  35       23909.4  34065.3    12732.6  16581.4         27.1067
 36  36       25126.9  35579.9    13147.9  17251.6         26.2000
 37  37       26884.8  37018.5    13605.2  17942.7         31.9286
 38  38       26766.2  38907.8    13813.9  18392.5         32.0870
 39  39       27573.1  39968.6    13965.5  18630.6         33.7895
 40  40       28495.0  42583.9    14314.0  18950.6         37.6000
 41  41       30515.6  44362.0    14699.9  19575.2         23.1429
 42  42       34258.1  46112.8    15529.5  20854.8         40.0000
 43  43       33678.4  44189.1    15930.9  21524.8         25.6000
 44  44       36578.5  46180.0    16316.0  22247.0         22.0000
 45  45       37774.7  47143.1    17745.1  23191.7         57.0000
 46  46       50460.5  50543.6    18372.5  24545.1             NaN
 47  47       39283.0  49083.2    19036.6  25725.6             NaN
 48  48       37967.1  51659.6    19244.9  26839.6             NaN
 49  49       49517.2  48002.2    21515.2  27969.2             NaN
 50  50       45412.0  54772.0    18504.2  23471.5             NaN

     평균 누적 와드 제거 횟수
 0           1.0000
 1           1.0250
 2           1.0000
 3           1.0263
 4           1.0744
 5           1.1403
 6           1.1855
 7           1.2955
 8           1.4027
 9           1.6005
 10          1.7555
 11          1.9914
 12          2.1620
 13          2.4260
 14          2.6663
 15          2.8510
 16          3.1342
 17          3.3919
 18          3.7370
 19          3.9469
 20          4.1642
 21          4.3720
 22          4.6348
 23          4.8897
 24          5.3113
 25          5.4732
 26          5.7616
 27          5.9217
 28          6.4662
 29          6.8611
 30          6.8596
 31          7.2808
 32          7.5000
 33          7.9300
 34          7.8070
 35          8.4091
 36          6.5714
 37          8.0909
 38          9.2500
 39          8.4286
 40          8.3333
 41          8.6667
 42          6.0000
 43          6.0000
 44             NaN
 45             NaN
 46          5.0000
 47          7.0000
 48             NaN
 49             NaN
 50             NaN  ,
 '트위스티드 페이트':      분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량  평균 누적 와드 설치 횟수  \
 0    0           0.0      0.0      500.0      0.0          1.0000
 1    1          32.8     39.8      508.7      0.4          1.0035
 2    2         216.6    248.9      635.2    234.9          1.0179
 3    3         557.8    682.9     1016.3    848.0          1.2863
 4    4         901.4   1126.0     1378.5   1344.6          1.9882
 5    5        1265.2   1594.2     1780.1   1900.4          2.2468
 6    6        1620.3   2061.9     2198.1   2448.0          2.6384
 7    7        2049.1   2592.7     2601.8   2904.8          3.3934
 8    8        2436.5   3115.0     3031.6   3438.3          3.5766
 9    9        2844.0   3680.9     3472.8   3979.8          4.0278
 10  10        3298.1   4327.9     3875.9   4456.5          4.7870
 11  11        3821.5   5108.6     4351.2   5025.5          4.9699
 12  12        4430.7   5927.0     4829.6   5548.9          5.4638
 13  13        4992.0   6692.8     5262.2   6023.8          6.1301
 14  14        5591.7   7495.3     5757.0   6570.3          6.3891
 15  15        6169.9   8325.6     6206.7   7061.2          6.9465
 16  16        6862.0   9078.4     6738.9   7646.1          7.4651
 17  17        7492.8   9909.7     7197.0   8160.7          7.7593
 18  18        8288.7  10844.3     7697.1   8708.4          8.3146
 19  19        9071.7  11698.1     8179.8   9312.4          8.7921
 20  20        9877.0  12598.4     8657.2   9973.1          8.9367
 21  21       10711.6  13597.7     9125.0  10732.1          9.7610
 22  22       11582.6  14656.5     9576.4  11501.1         10.0632
 23  23       12549.3  15751.9    10079.3  12305.0         10.5652
 24  24       13569.2  16857.0    10510.2  12907.4         10.9824
 25  25       14632.2  17972.8    11000.2  13504.4         11.4481
 26  26       15456.5  19012.3    11355.6  14012.2         11.8128
 27  27       16615.1  20153.8    11864.1  14578.7         12.4485
 28  28       17628.5  21540.4    12336.5  15114.4         13.0530
 29  29       18556.2  22612.6    12708.9  15579.2         13.6043
 30  30       19746.5  23788.0    13221.5  16207.0         14.2917
 31  31       20870.2  24757.2    13724.9  16719.4         13.5915
 32  32       21437.2  26589.5    14043.4  17273.8         14.5000
 33  33       22921.1  28032.8    14388.3  17700.7         15.3488
 34  34       24604.6  29027.0    14864.4  18145.1         15.2121
 35  35       24981.9  30042.6    15392.5  18665.4         15.9143
 36  36       25584.6  31406.5    15646.7  19213.0         18.5455
 37  37       27182.5  32167.5    16138.8  19819.7         20.1875
 38  38       27469.9  33301.4    16624.7  20150.3         20.0588
 39  39       28395.1  36337.8    16875.8  20749.7         27.8000
 40  40       29530.9  36668.0    16851.4  20764.4         18.0000
 41  41       30630.0  38151.3    17463.7  21299.6         20.6667
 42  42       33205.9  40581.7    18117.8  22040.7         22.7500
 43  43       35215.9  40998.3    18623.4  22697.5         17.0000
 44  44       33715.7  42734.2    18732.4  22491.2         22.3333
 45  45       36362.1  50779.6    18300.3  22724.3         23.0000
 46  46       36893.0  48508.7    20106.0  24536.0         26.0000
 47  47       34787.7  48143.7    16866.7  21797.3             NaN
 48  48       40368.0  57395.0    20007.5  25934.0             NaN

     평균 누적 와드 제거 횟수
 0           1.0000
 1           1.0769
 2           1.0000
 3           1.0000
 4           1.0263
 5           1.1215
 6           1.2465
 7           1.2895
 8           1.4877
 9           1.4870
 10          1.6000
 11          1.9067
 12          2.0505
 13          2.1878
 14          2.4362
 15          2.5535
 16          2.7072
 17          3.0478
 18          3.1359
 19          3.3900
 20          3.6667
 21          3.9064
 22          4.2741
 23          4.4279
 24          4.6707
 25          4.4887
 26          4.8505
 27          5.5922
 28          5.5663
 29          6.2740
 30          6.3182
 31          6.2619
 32          6.7667
 33          7.8519
 34          7.1053
 35          7.7778
 36          7.8889
 37          8.0000
 38         10.3333
 39          6.6667
 40          4.5000
 41          7.5000
 42          4.5000
 43         10.0000
 44          8.5000
 45         11.0000
 46             NaN
 47             NaN
 48             NaN  ,
 '신 짜오':      분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량  평균 누적 와드 설치 횟수  \
 0    0           0.0      0.0      500.0      0.0          1.0019
 1    1          29.9     48.5      509.8      0.5          1.0032
 2    2          99.4    893.2      623.8    277.6          1.0193
 3    3         281.6   1996.5     1021.0    709.7          1.5068
 4    4         660.9   2909.6     1444.1   1048.2          1.9390
 5    5        1010.3   3727.1     1824.1   1366.1          2.3440
 6    6        1332.6   4662.5     2196.1   1731.6          2.6252
 7    7        1719.5   5843.3     2550.7   2089.3          2.9970
 8    8        2095.0   7026.3     2924.2   2503.0          3.1959
 9    9        2539.5   8262.0     3321.5   2958.9          3.5042
 10  10        3084.2   9533.3     3730.2   3409.9          3.8121
 11  11        3713.8  10804.8     4147.3   3872.0          3.8814
 12  12        4400.4  12260.1     4542.4   4296.0          4.3780
 13  13        5070.7  13686.2     4956.1   4759.5          4.4934
 14  14        5758.9  15134.3     5394.1   5262.3          4.8991
 15  15        6498.3  16695.8     5849.4   5785.6          5.0404
 16  16        7218.4  18267.1     6283.5   6309.1          5.4930
 17  17        8021.0  19843.5     6731.6   6845.8          5.4366
 18  18        8900.6  21450.2     7183.3   7373.6          5.8005
 19  19        9812.6  22972.6     7617.5   7894.3          6.0843
 20  20       10759.3  24779.4     8032.3   8400.1          6.0725
 21  21       11686.2  26476.4     8431.7   8927.9          6.5062
 22  22       12649.2  28413.4     8873.4   9488.1          6.7920
 23  23       13907.4  30457.9     9369.6  10094.9          6.8899
 24  24       14815.0  32429.4     9769.9  10635.0          7.1469
 25  25       15826.6  34437.5    10142.6  11103.8          7.2332
 26  26       17014.9  36517.4    10618.7  11698.7          7.6364
 27  27       17934.7  38434.8    10983.3  12215.2          7.8035
 28  28       18777.4  39985.8    11342.9  12716.9          8.0191
 29  29       19996.8  42412.2    11732.1  13222.2          8.1926
 30  30       20917.3  44238.3    12138.9  13840.9          8.3469
 31  31       22376.7  46414.0    12565.0  14433.3          9.2647

# 챔피언 기본 정보 저장 함수

In [ ]:
# 챔피언 기본 스탯 추출 쿼리
def get_champion_main_stats(conn):
    main_stats_query = """
    SELECT 
        cp.champion_id,
        FLOOR(cs.timestamp / 60000) AS minute,
        ROUND(SUM(cs.tdd_to_champion), 1) AS total_tdd_to_champion,
        ROUND(SUM(cs.total_damage_taken), 1) AS total_damage_taken,
        ROUND(SUM(cs.total_gold), 1) AS total_gold,
        ROUND(SUM(cs.xp), 1) AS total_xp
    FROM 
        champion_stat_per_timestamp cs
    JOIN 
        champion_participant_id cp ON cs.match_id = cp.match_id AND cs.participant_id = cp.participant_id
    GROUP BY 
        cp.champion_id, FLOOR(cs.timestamp / 60000)
    ORDER BY 
        cp.champion_id, minute;
    """
    return pd.read_sql_query(main_stats_query, conn)

In [ ]:
def save_main_stats_to_pkl():
    conn = connect_db()
    champion_dict = get_champion_dict(conn)
    main_stats = get_champion_main_stats(conn)
    conn.close()

    column_mapping = {
        "minute": "분",
        "avg_tdd_to_champion": "챔피언에게 가한 피해량",
        "avg_total_damage_taken": "받은 피해량",
        "avg_total_gold": "총 획득한 골드량",
        "avg_xp": "총 경험치량",
    }
    champion_dataframes = {}
    for champion_id, champion_name in tqdm(champion_dict.items(), desc="Processing Champions"):
        champion_df = main_stats[main_stats['champion_id'] == champion_id].drop(columns=['champion_id'])
        champion_df = champion_df.rename(columns=column_mapping)
        champion_dataframes[champion_name] = champion_df
    with open("dashboard_data/champion_main_stats.pkl", "wb") as f:
        pickle.dump(champion_dataframes, f)

In [ ]:
with open("data/champion_main_stats.pkl", "rb") as f:
    champion_main_stats_data = pickle.load(f)
champion_main_stats_data['가렌']

{'애니':      분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 0    0           0.0      0.0      500.0      0.0
 1    1          51.1     38.8      515.8      0.7
 2    2         270.4    239.2      629.0    218.4
 3    3         616.7    574.5      962.6    805.3
 4    4         939.6    917.2     1279.3   1294.2
 5    5        1237.7   1274.8     1618.8   1828.5
 6    6        1625.4   1673.7     1957.4   2341.2
 7    7        2152.7   2084.7     2313.8   2814.0
 8    8        2647.7   2525.0     2692.2   3329.7
 9    9        3221.3   3003.7     3085.4   3841.4
 10  10        3751.6   3456.1     3439.8   4309.7
 11  11        4356.3   3983.3     3858.2   4845.2
 12  12        5051.5   4579.7     4283.4   5344.8
 13  13        5748.2   5174.8     4661.9   5768.5
 14  14        6489.0   5786.7     5086.3   6262.6
 15  15        7318.2   6399.1     5538.5   6744.0
 16  16        8179.9   7039.1     5918.6   7223.9
 17  17        9118.5   7711.3     6316.8   7695.9
 18  18       10078.8   8440.0     6760.1   8181.8
 19  19       11197.4   9053.0     7188.9   8702.6
 20  20       12250.3   9726.7     7580.4   9133.9
 21  21       13599.5  10656.3     7995.9   9639.7
 22  22       14483.7  11412.9     8373.3  10162.8
 23  23       15854.3  12173.7     8858.1  10703.6
 24  24       16717.5  13103.2     9080.6  11013.3
 25  25       18199.0  13992.2     9520.7  11521.9
 26  26       19086.2  14927.0     9854.7  11976.5
 27  27       20379.1  15820.1    10146.6  12372.3
 28  28       21384.8  16807.7    10510.7  12711.8
 29  29       23278.6  17715.9    10958.7  13334.4
 30  30       24498.9  18283.3    11426.6  13931.3
 31  31       26606.1  19520.0    11811.6  14400.2
 32  32       26449.6  20111.1    12068.5  14806.6
 33  33       29204.4  21501.2    12591.8  15538.3
 34  34       28535.2  21021.2    12664.6  15631.8
 35  35       27960.6  23505.1    12386.2  15705.2
 36  36       30858.7  23770.2    13304.5  16429.4
 37  37       34626.2  25428.9    14243.8  17955.5
 38  38       34622.9  26069.0    14024.1  18190.0
 39  39       36250.9  28674.4    14035.2  18111.1
 40  40       36592.6  27927.8    14536.8  19230.1
 41  41       41404.5  30839.3    14875.7  19177.9
 42  42       34934.0  24003.5    16380.0  21965.0
 43  43       35270.5  25604.5    16723.0  22313.5
 44  44       39424.0  25599.7    17681.3  22863.0
 45  45       29921.0  26904.0    17002.0  23990.0
 46  46       30778.0  30635.0    17225.0  24200.0,
 '올라프':      분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 47   0           0.0      0.0      500.0      0.0
 48   1          49.3     55.1      509.6      0.5
 49   2         346.8    417.2      603.3    165.7
 50   3         705.4   1005.3      969.6    771.3
 51   4        1033.4   1514.6     1282.9   1229.6
 52   5        1492.5   2134.0     1648.0   1781.2
 53   6        1937.5   2766.8     1995.1   2282.2
 54   7        2448.0   3462.6     2362.4   2772.2
 55   8        2980.1   4175.9     2756.1   3313.5
 56   9        3542.5   4936.7     3146.5   3850.7
 57  10        4150.0   5728.8     3523.8   4367.6
 58  11        4779.3   6603.8     3958.7   4937.0
 59  12        5470.6   7546.9     4399.7   5450.6
 60  13        6184.1   8513.9     4848.4   5951.1
 61  14        6923.0   9531.2     5370.0   6522.9
 62  15        7736.8  10647.1     5879.2   7076.2
 63  16        8424.5  11634.5     6319.2   7612.4
 64  17        9266.4  12851.7     6789.5   8149.4
 65  18       10130.0  14060.1     7293.4   8706.1
 66  19       11163.1  15285.9     7817.1   9295.3
 67  20       11991.3  16509.3     8240.7   9786.1
 68  21       13144.8  17968.8     8767.6  10385.6
 69  22       14130.5  19322.9     9285.5  10989.0
 70  23       15378.0  20837.1     9756.7  11548.1
 71  24       16639.6  22446.1    10228.1  12075.0
 72  25       17741.0  24015.5    10672.0  12604.0
 73  26       18599.9  25424.5    11114.1  13091.3
 74  27       19642.4  26977.9    11451.5  13563.5
 75  28       20859.1  28628.2    12035.7  14210.7
 76  29       21867.2  29949.9    12444.7  14784.6
 77  30       23018.1  31775.4    12757.5  15189.1
 78  31       24848.0  33496.8    13348.6  15957.3
 79  32       26138.1  35533.8    13752.2  16404.7
 80  33       27212.4  36618.3    14152.4  16900.4
 81  34       28630.5  38445.3    14575.7  17521.2
 82  35       29620.6  40589.1    15003.6  17921.3
 83  36       31413.6  42422.6    15392.2  18385.8
 84  37       31828.7  43234.5    15851.8  19149.2
 85  38       32972.9  44867.3    16182.8  19691.7
 86  39       36451.5  48580.9    16617.0  20149.8
 87  40       32221.8  49297.5    16487.8  20103.6
 88  41       33098.2  51306.6    17693.8  21708.1
 89  42       26384.4  46570.4    17569.3  22087.3
 90  43       34604.7  52578.9    18008.1  23425.3
 91  44       40163.0  54116.3    18976.7  24720.0
 92  45       40214.3  54410.7    19429.3  25436.0
 93  46       42101.0  58067.0    19889.7  25970.0
 94  47       42788.8  60547.2    20668.8  26926.2
 95  48       46122.5  62530.0    19818.0  27129.5
 96  49       51017.0  67333.0    20497.5  27672.5
 97  50       53066.0  69016.3    20518.3  27659.3
 98  51       47518.0  69671.5    22041.0  29163.0,
 '갈리오':       분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 99    0           0.0      0.0      500.0      0.0
 100   1          29.9     47.9      505.1      0.4
 101   2         201.7    333.1      595.9    213.4
 102   3         553.6    872.4      916.6    798.4
 103   4         918.0   1377.0     1240.6   1280.0
 104   5        1332.0   1930.4     1593.7   1800.8
 105   6        1730.8   2476.6     1946.4   2316.3
 106   7        2174.2   3057.2     2287.5   2751.1
 107   8        2617.3   3666.4     2662.8   3255.5
 108   9        3087.0   4327.2     3036.1   3758.6
 109  10        3586.5   5035.1     3373.5   4209.7
 110  11        4190.7   5873.8     3777.1   4731.0
 111  12        4849.4   6756.5     4184.8   5215.8
 112  13        5461.4   7586.7     4548.5   5645.9
 113  14        6076.6   8460.2     4956.6   6144.6
 114  15        6749.8   9418.3     5362.0   6620.7
 115  16        7393.7  10339.8     5754.2   7126.0
 116  17        8133.8  11320.6     6157.0   7614.2
 117  18        8852.5  12342.0     6553.0   8092.2
 118  19        9625.1  13410.3     6934.9   8566.1
 119  20       10369.5  14461.2     7303.1   9021.2
 120  21       11189.0  15647.4     7668.6   9515.4
 121  22       12061.8  16799.5     8078.6  10056.1
 122  23       12951.0  18124.5     8432.5  10543.4
 123  24       13878.9  19412.1     8826.1  11042.6
 124  25       14891.1  20719.2     9211.5  11528.5
 125  26       15838.5  22015.3     9587.7  12033.7
 126  27       16666.9  23304.0     9967.5  12546.9
 127  28       17448.1  24568.6    10294.0  13004.1
 128  29       18523.1  25989.6    10695.8  13537.8
 129  30       19536.3  27399.7    11032.1  14058.5
 130  31       20442.2  29179.8    11406.5  14616.2
 131  32       21376.9  30587.7    11701.2  15061.7
 132  33       22205.3  31781.0    12041.6  15550.9
 133  34       22942.5  32992.4    12437.7  16141.0
 134  35       23909.4  34065.3    12732.6  16581.4
 135  36       25126.9  35579.9    13147.9  17251.6
 136  37       26884.8  37018.5    13605.2  17942.7
 137  38       26766.2  38907.8    13813.9  18392.5
 138  39       27573.1  39968.6    13965.5  18630.6
 139  40       28495.0  42583.9    14314.0  18950.6
 140  41       30515.6  44362.0    14699.9  19575.2
 141  42       34258.1  46112.8    15529.5  20854.8
 142  43       33678.4  44189.1    15930.9  21524.8
 143  44       36578.5  46180.0    16316.0  22247.0
 144  45       37774.7  47143.1    17745.1  23191.7
 145  46       50460.5  50543.6    18372.5  24545.1
 146  47       39283.0  49083.2    19036.6  25725.6
 147  48       37967.1  51659.6    19244.9  26839.6
 148  49       49517.2  48002.2    21515.2  27969.2
 149  50       45412.0  54772.0    18504.2  23471.5,
 '트위스티드 페이트':       분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 150   0           0.0      0.0      500.0      0.0
 151   1          32.8     39.8      508.7      0.4
 152   2         216.6    248.9      635.2    234.9
 153   3         557.8    682.9     1016.3    848.0
 154   4         901.4   1126.0     1378.5   1344.6
 155   5        1265.2   1594.2     1780.1   1900.4
 156   6        1620.3   2061.9     2198.1   2448.0
 157   7        2049.1   2592.7     2601.8   2904.8
 158   8        2436.5   3115.0     3031.6   3438.3
 159   9        2844.0   3680.9     3472.8   3979.8
 160  10        3298.1   4327.9     3875.9   4456.5
 161  11        3821.5   5108.6     4351.2   5025.5
 162  12        4430.7   5927.0     4829.6   5548.9
 163  13        4992.0   6692.8     5262.2   6023.8
 164  14        5591.7   7495.3     5757.0   6570.3
 165  15        6169.9   8325.6     6206.7   7061.2
 166  16        6862.0   9078.4     6738.9   7646.1
 167  17        7492.8   9909.7     7197.0   8160.7
 168  18        8288.7  10844.3     7697.1   8708.4
 169  19        9071.7  11698.1     8179.8   9312.4
 170  20        9877.0  12598.4     8657.2   9973.1
 171  21       10711.6  13597.7     9125.0  10732.1
 172  22       11582.6  14656.5     9576.4  11501.1
 173  23       12549.3  15751.9    10079.3  12305.0
 174  24       13569.2  16857.0    10510.2  12907.4
 175  25       14632.2  17972.8    11000.2  13504.4
 176  26       15456.5  19012.3    11355.6  14012.2
 177  27       16615.1  20153.8    11864.1  14578.7
 178  28       17628.5  21540.4    12336.5  15114.4
 179  29       18556.2  22612.6    12708.9  15579.2
 180  30       19746.5  23788.0    13221.5  16207.0
 181  31       20870.2  24757.2    13724.9  16719.4
 182  32       21437.2  26589.5    14043.4  17273.8
 183  33       22921.1  28032.8    14388.3  17700.7
 184  34       24604.6  29027.0    14864.4  18145.1
 185  35       24981.9  30042.6    15392.5  18665.4
 186  36       25584.6  31406.5    15646.7  19213.0
 187  37       27182.5  32167.5    16138.8  19819.7
 188  38       27469.9  33301.4    16624.7  20150.3
 189  39       28395.1  36337.8    16875.8  20749.7
 190  40       29530.9  36668.0    16851.4  20764.4
 191  41       30630.0  38151.3    17463.7  21299.6
 192  42       33205.9  40581.7    18117.8  22040.7
 193  43       35215.9  40998.3    18623.4  22697.5
 194  44       33715.7  42734.2    18732.4  22491.2
 195  45       36362.1  50779.6    18300.3  22724.3
 196  46       36893.0  48508.7    20106.0  24536.0
 197  47       34787.7  48143.7    16866.7  21797.3
 198  48       40368.0  57395.0    20007.5  25934.0,
 '신 짜오':       분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 199   0           0.0      0.0      500.0      0.0
 200   1          29.9     48.5      509.8      0.5
 201   2          99.4    893.2      623.8    277.6
 202   3         281.6   1996.5     1021.0    709.7
 203   4         660.9   2909.6     1444.1   1048.2
 204   5        1010.3   3727.1     1824.1   1366.1
 205   6        1332.6   4662.5     2196.1   1731.6
 206   7        1719.5   5843.3     2550.7   2089.3
 207   8        2095.0   7026.3     2924.2   2503.0
 208   9        2539.5   8262.0     3321.5   2958.9
 209  10        3084.2   9533.3     3730.2   3409.9
 210  11        3713.8  10804.8     4147.3   3872.0
 211  12        4400.4  12260.1     4542.4   4296.0
 212  13        5070.7  13686.2     4956.1   4759.5
 213  14        5758.9  15134.3     5394.1   5262.3
 214  15        6498.3  16695.8     5849.4   5785.6
 215  16        7218.4  18267.1     6283.5   6309.1
 216  17        8021.0  19843.5     6731.6   6845.8
 217  18        8900.6  21450.2     7183.3   7373.6
 218  19        9812.6  22972.6     7617.5   7894.3
 219  20       10759.3  24779.4     8032.3   8400.1
 220  21       11686.2  26476.4     8431.7   8927.9
 221  22       12649.2  28413.4     8873.4   9488.1
 222  23       13907.4  30457.9     9369.6  10094.9
 223  24       14815.0  32429.4     9769.9  10635.0
 224  25       15826.6  34437.5    10142.6  11103.8
 225  26       17014.9  36517.4    10618.7  11698.7
 226  27       17934.7  38434.8    10983.3  12215.2
 227  28       18777.4  39985.8    11342.9  12716.9
 228  29       19996.8  42412.2    11732.1  13222.2
 229  30       20917.3  44238.3    12138.9  13840.9
 230  31       22376.7  46414.0    12565.0  14433.3
 231  32       23275.0  48320.7    13027.3  15036.2
 232  33       24199.7  50278.1    13331.8  15497.8
 233  34       25364.3  52044.7    13675.4  16035.3
 234  35       26104.9  54109.9    14057.7  16537.8
 235  36       26895.1  55868.1    14343.4  16995.1
 236  37       28787.8  57456.9    14885.9  17572.5
 237  38       28481.6  59272.8    15200.8  18133.6
 238  39       29883.1  60606.0    15623.8  18636.7
 239  40       30074.5  64899.6    16229.4  19544.6
 240  41       31494.4  67157.3    16503.8  19718.8
 241  42       33012.2  73469.0    16595.9  20390.8
 242  43       28562.2  70713.6    16936.4  20799.5
 243  44       33092.2  71968.8    18402.3  21907.7
 244  45       55032.7  68384.3    22778.3  28451.3
 245  46       48813.5  93184.0    21143.5  23999.0,
 '우르곳':       분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 246   0           0.0      0.0      500.0      0.0
 247   1          53.7     50.2      511.4      0.6
 248   2         402.5    307.6      594.3    164.0
 249   3         767.7    700.1      964.6    815.1
 250   4        1134.7   1115.3     1282.9   1296.9
 251   5        1510.5   1567.5     1632.6   1859.6
 252   6        1863.3   2021.1     1968.5   2385.8
 253   7        2271.7   2529.1     2318.0   2873.7
 254   8        2702.2   3078.9     2695.1   3430.1
 255   9        3150.6   3633.7     3060.1   3955.9
 256  10        3632.4   4262.4     3415.0   4481.2
 257  11        4214.5   5022.2     3831.5   5060.8
 258  12        4899.1   5846.4     4278.3   5597.6
 259  13        5598.2   6716.5     4709.1   6090.2
 260  14        6329.1   7614.6     5234.1   6682.4
 261  15        7076.9   8571.8     5759.6   7235.0
 262  16        7767.2   9453.3     6213.8   7775.0
 263  17        8628.6  10498.5     6723.8   8335.4
 264  18        9487.3  11626.2     7222.3   8871.9
 265  19       10353.4  12704.8     7717.3   9392.8
 266  20       11369.9  13914.2     8222.2   9950.3
 267  21       12334.5  15083.2     8720.8  10522.0
 268  22       13403.4  16356.3     9217.0  11088.7
 269  23       14618.9  17868.0     9736.2  11659.2
 270  24       15693.2  19196.9    10236.2  12215.1
 271  25       16810.4  20523.5    10636.9  12685.0
 272  26       18026.2  21941.5    11139.2  13210.9
 273  27       18999.2  23666.9    11550.9  13691.6
 274  28       20570.8  25188.3    12165.4  14325.1
 275  29       21304.0  26541.2    12588.4  14871.5
 276  30       22301.7  28339.1    13047.3  15383.2
 277  31       24442.4  29833.6    13653.8  16174.1
 278  32       26274.9  32256.7    14285.2  16729.0
 279  33       27017.0  33105.5    14698.7  17357.8
 280  34       28149.9  35108.2    15189.9  17777.2
 281  35       28529.7  36083.9    15420.0  18255.7
 282  36       30695.3  37838.7    15979.8  18784.5
 283  37       31691.1  40135.7    16418.0  19281.4
 284  38       31480.5  40703.0    16305.9  19877.6
 285  39       36035.9  45158.4    17279.1  20469.0
 286  40       32660.5  46672.0    17083.9  21565.6
 287  41       40384.9  51347.7    18064.0  22325.1
 288  42       40366.8  52120.8    19083.5  23447.5
 289  43       32970.0  51381.6    18572.4  23946.8
 290  44       42458.0  50513.5    19588.5  24810.5
 291  45       43672.5  52087.0    20661.5  25149.0
 292  46       51139.7  55865.7    22142.3  27500.0
 293  47       35495.0  52511.0    18705.0  21659.0
 294  48       35756.0  54021.0    19068.0  22447.0
 295  49       35756.0  57327.0    19596.0  23225.0
 296  50       39719.0  62933.0    19836.0  23619.0
 297  51       39866.0  64333.0    20286.0  25441.0
 298  52       41173.0  67526.0    21265.5  27073.5,
 '르블랑':       분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 299   0           0.0      0.0      500.0      0.0
 300   1          43.1     41.7      508.8      0.4
 301   2         290.3    291.0      618.3    230.1
 302   3         754.5    734.1      965.6    823.2
 303   4        1206.9   1171.6     1320.3   1316.9
 304   5        1684.1   1641.0     1702.0   1858.3
 305   6        2171.6   2122.0     2067.1   2376.6
 306   7        2712.0   2623.0     2440.4   2843.0
 307   8        3276.7   3158.0     2846.3   3369.1
 308   9        3851.9   3716.3     3244.1   3873.5
 309  10        4480.8   4327.1     3616.7   4352.0
 310  11        5202.2   5016.2     4053.9   4898.0
 311  12        6017.0   5765.3     4510.4   5404.5
 312  13        6797.2   6481.4     4915.0   5854.5
 313  14        7577.4   7216.1     5365.9   6374.2
 314  15        8455.8   8025.1     5830.4   6885.6
 315  16        9281.5   8770.3     6262.6   7396.9
 316  17       10175.4   9545.3     6700.8   7896.0
 317  18       11170.7  10421.5     7149.7   8397.5
 318  19       12154.5  11277.9     7570.5   8881.2
 319  20       13119.8  12150.2     8000.3   9353.8
 320  21       14162.9  13072.8     8431.0   9880.4
 321  22       15186.3  14019.2     8856.7  10371.2
 322  23       16507.2  15030.8     9325.3  10913.6
 323  24       17734.8  16047.0     9770.9  11421.3
 324  25       18756.6  17115.9    10104.3  11814.9
 325  26       20152.6  18141.5    10617.7  12415.7
 326  27       21224.6  19225.4    11002.4  12866.6
 327  28       22691.5  20356.8    11476.3  13434.3
 328  29       23855.6  21432.4    11842.0  13843.8
 329  30       25158.4  22398.0    12317.9  14496.8
 330  31       26737.8  23432.7    12734.5  15019.9
 331  32       27520.3  24576.1    13052.1  15430.6
 332  33       28937.2  25692.0    13483.5  15923.5
 333  34       30088.8  26824.0    13788.3  16415.5
 334  35       31673.8  27893.1    14252.1  16874.1
 335  36       32755.0  28975.3    14669.6  17446.2
 336  37       35056.1  30402.5    15083.0  17923.7
 337  38       35006.5  31137.2    15290.1  18313.9
 338  39       37313.6  32205.0    15850.6  18797.0
 339  40       40173.1  35040.3    16615.0  19785.4
 340  41       40566.0  35259.7    16472.6  19782.5
 341  42       41508.0  36229.7    16831.6  20145.4
 342  43       42419.2  38103.8    17416.8  21251.1
 343  44       43400.5  38751.4    17467.1  21115.5
 344  45       35145.8  38854.5    16576.1  19472.1
 345  46       41704.4  39149.4    17814.6  22986.2
 346  47       44725.0  41011.5    17427.8  21170.8
 347  48       41477.5  38662.5    17705.2  22200.2,
 '블라디미르':       분  챔피언에게 가한 피해량   받은 피해량  총 획득한 골드량   총 경험치량
 348   0           0.0      0.0      500.0      0.0
 349   1          21.9     29.4      504.7      0.2
 350   2         250.8    313.0      589.6    173.2
 351   3         667.9    873.7      935.6    805.3
 352   4        1076.8   1399.3     1269.7   1358.8
 353   5        1501.1   1972.4     1616.0   1917.3
 354   6        1942.7   2579.8     1954.1   2448.9
 355   7        2469.2   3264.2     2305.9   2968.0
 356   8        3049.2   4021.6     2686.2   3532.6
 357   9        3670.8   4846.7     3065.9   4087.0
 358  10        4359.4   5764.2     3432.1   4622.5
 359  11        5133.8   6764.9     3843.4   5209.8
 360  12        5949.4   7812.8     4272.6   5752.9
 361  13        6771.8   8890.7     4674.3   6262.3
 362  14        7623.2  10047.3     5138.7   6846.3
 363  15        8502.1  11186.7     5602.0   7382.0
 364  16        9277.7  12270.2     6020.2   7921.3
 365  17       10181.4  13452.2     6473.1   8479.0
 366  18       11181.0  14734.7     6939.8   9013.8
 367  19       12166.8  15999.7     7382.6   9536.2
 368  20       13241.6  17313.7     7833.0  10061.8
 369  21       14315.0  18684.5     8272.1  10608.0
 370  22       15400.6  20104.5     8722.0  11173.8
 371  23       16633.2  21653.0     9155.8  11717.3
 372  24       17965.5  23240.2     9604.8  12222.2
 373  25       19205.3  24799.7    10005.0  12693.2
 374  26       20693.9  26514.5    10452.8  13248.4
 375  27       21820.5  27957.4    10917.6  13846.1
 376  28       23234.9  29726.1    11391.6  14399.6

# 와드

In [ ]:
# 와드 제거 횟수 데이터 추출
def get_ward_removal_stats(conn):
    ward_removal_query = """
    WITH filtered_ward_kills AS (
        SELECT 
            wk.match_id,
            cp.champion_id,
            FLOOR(wk.timestamp / 60000) AS minute,
            COUNT(*) AS ward_removals
        FROM 
            ward_kill wk
        JOIN 
            champion_participant_id cp ON wk.match_id = cp.match_id AND wk.participant_id = cp.participant_id
        WHERE 
            wk.ward_type != 'UNDEFINED'
        GROUP BY 
            wk.match_id, cp.champion_id, minute
    ),
    cumulative_ward_removals AS (
        SELECT 
            match_id,
            champion_id,
            minute,
            SUM(ward_removals) OVER (PARTITION BY match_id, champion_id ORDER BY minute ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_removals
        FROM 
            filtered_ward_kills
    )
    SELECT 
        champion_id,
        minute,
        AVG(cumulative_removals) AS avg_cumulative_ward_removals
    FROM 
        cumulative_ward_removals
    GROUP BY 
        champion_id, minute
    ORDER BY 
        champion_id, minute;
    """
    return pd.read_sql_query(ward_removal_query, conn)

# 와드 설치 횟수 데이터 추출
def get_ward_placement_stats(conn):
    ward_placement_query = """
    WITH filtered_ward_placements AS (
        SELECT 
            wp.match_id,
            cp.champion_id,
            FLOOR(wp.timestamp / 60000) AS minute,
            COUNT(*) AS ward_placements
        FROM 
            ward_placed wp
        JOIN 
            champion_participant_id cp ON wp.match_id = cp.match_id AND wp.participant_id = cp.participant_id
        GROUP BY 
            wp.match_id, cp.champion_id, minute
    ),
    cumulative_ward_placements AS (
        SELECT 
            match_id,
            champion_id,
            minute,
            SUM(ward_placements) OVER (PARTITION BY match_id, champion_id ORDER BY minute ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_placements
        FROM 
            filtered_ward_placements
    )
    SELECT 
        champion_id,
        minute,
        AVG(cumulative_placements) AS avg_cumulative_ward_placements
    FROM 
        cumulative_ward_placements
    GROUP BY 
        champion_id, minute
    ORDER BY 
        champion_id, minute;
    """
    return pd.read_sql_query(ward_placement_query, conn)

def save_ward_removal_stats_to_pkl():
    conn = connect_db()
    ward_removal_stats = get_ward_removal_stats(conn)
    ward_placement_stats = get_ward_placement_stats(conn)
    conn.close()  
    with open("table_data/ward_removal_stats.pkl", "wb") as f:
        pickle.dump(ward_removal_stats, f)
    with open("table_data/ward_placement_stats.pkl", "wb") as f:
        pickle.dump(ward_placement_stats, f)

C:\Users\dgjja\AppData\Local\Temp\ipykernel_7004\3701261899.py:39: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(ward_removal_query, conn)
C:\Users\dgjja\AppData\Local\Temp\ipykernel_7004\3701261899.py:77: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(ward_placement_query, conn)

In [ ]:
save_ward_removal_stats_to_pkl()

## 챔피언별 와드제거 데이터 저장

In [33]:
def save_champion_ward_removal_stats_to_pkl():
    conn = connect_db()
    champion_dict = get_champion_dict(conn)
    conn.close()  
    with open("table_data/ward_removal_stats.pkl", "rb") as f:
        ward_removal_stats = pickle.load(f)
    column_mapping = {
        "minute": "분",
        "avg_cumulative_ward_removals": "평균 누적 와드 제거 횟수",
    }
    champion_dataframes = {}
    for champion_id, champion_name in tqdm(champion_dict.items(), desc="Processing Champions"):
        removal_df = ward_removal_stats[ward_removal_stats['champion_id'] == champion_id][['minute', 'avg_cumulative_ward_removals']]
        removal_df = removal_df.rename(columns=column_mapping)
        champion_dataframes[champion_name] = removal_df
    with open("dashboard_data/champion_ward_removal_stats.pkl", "wb") as f:
        pickle.dump(champion_dataframes, f)

In [34]:
save_champion_ward_removal_stats_to_pkl()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_7004\3920025925.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_dict = pd.read_sql_query(champion_dict_query, conn)
Processing Champions: 100%|██████████| 168/168 [00:00<00:00, 962.57it/s]

## 챔피언별 와드 설치 데이터 저장

In [35]:
def save_champion_ward_placement_stats_to_pkl():
    conn = connect_db()
    champion_dict = get_champion_dict(conn)
    conn.close()  
    with open("table_data/ward_placement_stats.pkl", "rb") as f:
        ward_placement_stats = pickle.load(f)
    column_mapping = {
        "minute": "분",
        "avg_cumulative_ward_placements": "평균 누적 와드 설치 횟수",
    }
    champion_dataframes = {}
    for champion_id, champion_name in tqdm(champion_dict.items(), desc="Processing Champions"):
        placement_df = ward_placement_stats[ward_placement_stats['champion_id'] == champion_id][['minute', 'avg_cumulative_ward_placements']]
        placement_df = placement_df.rename(columns=column_mapping)
        champion_dataframes[champion_name] = placement_df
    with open("dashboard_data/champion_ward_placement_stats.pkl", "wb") as f:
        pickle.dump(champion_dataframes, f)

In [37]:
save_champion_ward_placement_stats_to_pkl()

C:\Users\dgjja\AppData\Local\Temp\ipykernel_7004\3920025925.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  champion_dict = pd.read_sql_query(champion_dict_query, conn)
Processing Champions: 100%|██████████| 168/168 [00:00<00:00, 1027.02it/s]

In [39]:
with open('dashboard_data/champion_main_stats.pkl','rb') as f:
    data = pickle.load(f)
data['닐라'].head(5)

      분  챔피언에게 가한 피해량  받은 피해량  총 획득한 골드량  총 경험치량
8116  0           0.0     0.0      500.0     0.0
8117  1          34.2    35.2      509.9     0.4
8118  2         200.7   291.4      601.6   116.0
8119  3         444.2   726.2      962.4   577.5
8120  4         783.0  1158.6     1360.6   988.3

# 챔피언 승률

In [58]:
def get_champion_win_pick_rate():
    with open('table_data/champion_participant_id.pkl', 'rb') as f:
        champion_participant_id = pickle.load(f)
    with open('table_data/game_end.pkl', 'rb') as f:
        game_end = pickle.load(f)
    with open('table_data/champion_dict.pkl', 'rb') as f:
        champion_dict = pickle.load(f)

    # 데이터 복사
    champion_participant_df = champion_participant_id.copy()
    game_end_df = game_end.copy()
    champion_dict_df = champion_dict[['champion_id', 'champion_name']]

    # 팀 정보 추가
    champion_participant_df['team'] = champion_participant_df['participant_id'].apply(lambda x: 100 if x <= 5 else 200)

    # game_end_df와 병합하여 각 챔피언이 승리했는지 여부 계산
    merged_df = champion_participant_df.merge(game_end_df[['match_id', 'winning_team']], on='match_id')
    merged_df['win'] = merged_df['team'] == merged_df['winning_team']

    # 각 position, champion_id별로 승리 횟수, 총 픽 횟수 집계
    grouped_df = merged_df.groupby(['position', 'champion_id']).agg(
        total_picks=('match_id', 'count'),
        wins=('win', 'sum')
    ).reset_index()

    # 포지션별 경기 수 집계
    position_match_counts = merged_df.groupby('position')['match_id'].nunique().reset_index(name='position_match_counts')
    grouped_df = grouped_df.merge(position_match_counts, on='position')

    # 승률 및 픽률 계산
    grouped_df['win_rate'] = (grouped_df['wins'] / grouped_df['total_picks']).round(4)
    grouped_df['pick_rate'] = (grouped_df['total_picks'] / grouped_df['position_match_counts']).round(4)

    # 챔피언 이름을 추가하기 위해 champion_dict와 병합
    grouped_df = grouped_df.merge(champion_dict_df, on='champion_id')

    # 최종 결과물 구성, 컬럼 이름 수정 및 필요 없는 컬럼 제거
    result_df = grouped_df[['champion_name', 'win_rate', 'pick_rate', 'total_picks']]
    result_df.columns = ['챔피언', '승률', '픽률', '표본 수']

    # 포지션별로 데이터프레임을 분리하여 딕셔너리에 저장
    position_dict = {position: df for position, df in result_df.groupby(grouped_df['position'])}

    with open("dashboard_data/champion_win_pick_rate.pkl", "wb") as f:
        pickle.dump(position_dict, f)

In [59]:
get_champion_win_pick_rate()

In [60]:
with open('dashboard_data/champion_win_pick_rate.pkl', 'rb') as f:
    champion_dict = pickle.load(f)

In [64]:
champion_dict['BOTTOM'].sort_values(by='픽률', ascending=False)

     챔피언      승률      픽률   표본 수
89     진  0.4923  0.2865  17140
16    애쉬  0.5130  0.2324  13902
79   카이사  0.4918  0.2261  13526
27   코르키  0.5270  0.1323   7912
92   징크스  0.5109  0.1298   7768
..   ...     ...     ...    ...
28   카르마  0.5000  0.0000      2
26  갱플랭크  0.0000  0.0000      1
86    카밀  1.0000  0.0000      1
88   브라움  0.0000  0.0000      1
24    소나  0.0000  0.0000      1

[122 rows x 4 columns]

In [41]:
position_dict['BOTTOM']['pick_rate'].sum()

2.0000668605622973

In [42]:
position_dict['MIDDLE'].sort_values(by='pick_rate', ascending=False)

     champion_id position  win_rate  pick_rate
369          517   MIDDLE  0.509899   0.186591
374          777   MIDDLE  0.486168   0.147428
283           61   MIDDLE  0.497893   0.111089
269           42   MIDDLE  0.510802   0.097483
312          103   MIDDLE  0.497837   0.096597
..           ...      ...       ...        ...
256           28   MIDDLE  0.000000   0.000017
379          895   MIDDLE  1.000000   0.000017
364          421   MIDDLE  0.000000   0.000017
348          222   MIDDLE  1.000000   0.000017
264           37   MIDDLE  0.000000   0.000017

[155 rows x 4 columns]

In [33]:
position_dict['TOP'].sort_values(by='pick_rate', ascending=False)

     champion_id position  win_rate  pick_rate
542          897      TOP  0.494397   0.180473
407           24      TOP  0.515368   0.138134
497          150      TOP  0.505318   0.110019
540          893      TOP  0.522938   0.079430
437           58      TOP  0.494810   0.077291
..           ...      ...       ...        ...
534          555      TOP  1.000000   0.000017
432           53      TOP  1.000000   0.000017
411           28      TOP  1.000000   0.000017
461           89      TOP  0.000000   0.000017
483          120      TOP  0.000000   0.000017

[162 rows x 4 columns]

In [35]:
position_dict['TOP']['pick_rate'].sum()

2.000083575702871